apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nurettinsenbackend/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*.py"
            dest: .
